services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - ml
    volumes:
      - uploads-data:/app/uploads
    extra_hosts:
      - "host.docker.internal:host-gateway"

  ml:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    ports:
      - "8000:8000"
    volumes:
      - uploads-data:/app/uploads

volumes:
  uploads-data:
